theDays = [
  { en: "Monday", fr: "Lundi", ar: 'يوم الاثنين' },
  { en: "Tuesday", fr: "Mardi", ar: 'يوم الثلاثاء' },
  { en: "Wednesday", fr: "Mercredi", ar: 'يوم الأربعاء' },
  { en: "Thursday", fr: "Jeudi", ar: 'يوم الخميس' },
  { en: "Friday", fr: "Vendredi", ar: 'يوم الجمعة' },
  { en: "Saturday", fr: "Samedi", ar: 'يوم السبت' },
  { en: "Sunday", fr: "Dimanche", ar: 'يوم الأحد' },
]

theMonths = [
  { en: "January", fr: "Janvier" },
  { en: "February", fr: "Février" },
  { en: "March", fr: "Mars" },
  { en: "April", fr: "Avril" },
  { en: "May", fr: "Mai" },
  { en: "June", fr: "Juin" },
  { en: "July", fr: "Juillet" },
  { en: "August", fr: "Août" },
  { en: "September", fr: "Septembre" },
  { en: "October", fr: "Octobre" },
  { en: "November", fr: "Novembre" },
  { en: "December", fr: "Décembre" },
]

theNumbers = [
  { en: "Zero", fr: "Zéro" },
  { en: "One", fr: "Un" },
  { en: "Two", fr: "Deux" },
  { en: "Three", fr: "Trois" },
  { en: "Four", fr: "Quatre" },
  { en: "Five", fr: "Cinq" },
  { en: "Six", fr: "Six" },
  { en: "Seven", fr: "Sept" },
  { en: "Eight", fr: "Huit" },
  { en: "Nine", fr: "Neuf" },
  { en: "ten", fr: "Dix" },
]

thePeople = [
  { en: "son", fr: "fils" },
  { en: "daughter", fr: "fille" },
  { en: "child", fr: "enfant" },
  { en: "brother", fr: "frère" },
  { en: "sister", fr: "soeur" },
  { en: "mother", fr: "maman" },
  { en: "father", fr: "papa" },
  { en: "family", fr: "famille" },
  { en: "grandmother", fr: "grand-mère" },
  { en: "cousin", fr: "cousin" },
  { en: "uncle", fr: "oncle" },
  { en: "aunt", fr: "tante" },
  { en: "grandfather", fr: "grand-père" },
  { en: "siblings", fr: "frères et soeurs" },
  { en: "parents", fr: "parents" },
  { en: "spouse", fr: "conjoint" },
  { en: "wife", fr: "épouse" },
  { en: "friend", fr: "ami" },
  { en: "boy", fr: "garçon" },
  { en: "girl", fr: "fille" },
  { en: "man ", fr: "homme" },
  { en: "woman", fr: "femme" },
  { en: "kid", fr: "enfant" },
]

theAnimals = [
  { en: "pet", fr: "animal de compagnie" },
  { en: "cat", fr: "chat " },
  { en: "goldfish", fr: "poisson rouge" },
  { en: "fish", fr: "poisson" },
  { en: "hamster", fr: "hamster" },
  { en: "lizard", fr: "lézard" },
  { en: "parrot", fr: "perroquet" },
  { en: "rabbit", fr: "lapin" },
  { en: "tortoise", fr: "tortue" },
  { en: "budgie", fr: "perruche" },
  { en: "kangaroo", fr: "kangourou" },
]

theJobs = [
  { en: "job", fr: "travail" },
  { en: "work", fr: "travail" },
  { en: "shop assistant", fr: "vendeur" },
  { en: "scientific researcher", fr: "chercheur scientifique" },
  { en: "nurse", fr: "infirmier" },
  { en: "detective", fr: "détective" },
  { en: "lawyer", fr: "avocat" },
  { en: "receptionist", fr: "réceptionniste" },
  { en: "barista", fr: "barista" },
  { en: "pilot", fr: "pilote" },
  { en: "company director", fr: "directeur d'entreprise" },
  { en: "firefighter", fr: "sapeur pompier" },
  { en: "waiter", fr: "serveur" },
  { en: "photographer", fr: "photographe" },
  { en: "agent", fr: "agent" },
  { en: "teacher", fr: "professeur" },
  { en: "driver", fr: "conducteur" },
  { en: "student", fr: "étudiant" },
  { en: "journalist", fr: "journaliste" },
]
 
theFoods = [
  { en: "wine", fr: "vin" },
  { en: "appetizer/starter", fr: "entrée" },
  { en: "main course", fr: "plat principal" },
  { en: "calamari", fr: "calamar" },
  { en: "ice", fr: "glace" },
  { en: "water", fr: "eau" },
  { en: "egg", fr: "oeuf" },
  { en: "mushroom", fr: "champignon" },
  { en: "chicken", fr: "poulet" },
  { en: "rice", fr: "riz" },
  { en: "pie", fr: "tarte" },
  { en: "meat", fr: "viande" },
  { en: "apple", fr: "pomme" },
  { en: "pear", fr: "poire" },
  { en: "fruit", fr: "fruit" },
  { en: "orange", fr: "orange" },
  { en: "banana", fr: "banane" },
  { en: "juice", fr: "jus" },
  { en: "cake", fr: "gâteau" },
  { en: "ice cream", fr: "crème glacée" },
  { en: "salad", fr: "salade" },
  { en: "burger", fr: "hamburger" },
  { en: "noodle", fr: "nouille" },
  { en: "breakfast", fr: "petit-déjeuner" },
  { en: "coffee", fr: "café" },
]

theMoments = [
 { en: "from", fr: "de/depuis" },
 { en: "now", fr: "maintenant" },
 { en: "time", fr: "temps " },
 { en: "today", fr: "aujourd'hui" },
 { en: "tomorrow", fr: "demain" },
 { en: "yesterday", fr: "hier" },
 { en: "present", fr: "présent" },
 { en: "future", fr: "futur" },
 { en: "past", fr: "passé" },
 { en: "after", fr: "après" },
 { en: "before", fr: "avant" },
 { en: "hardly", fr: "à peine" },
 { en: "ever", fr: "jamais" },
 { en: "sometimes", fr: "parfois" },
 { en: "rarely", fr: "rarement" },
 { en: "never", fr: "jamais" },
 { en: "usually", fr: "habituellement" },
 { en: "occasionally", fr: "occasionnellement" },
 { en: "always", fr: "toujours" },
 { en: "often", fr: "souvent" },
 { en: "last", fr: "dernier" },
 { en: "next", fr: "suivant" },
]

theLocations = [
  { en: "below", fr: "en dessous" },
  { en: "above", fr: "au-dessus" },
  { en: "left", fr: "gauche" },
  { en: "right", fr: "droite" },
  { en: "back", fr: "arrière" },
  { en: "Behind", fr: "derrière" },
  { en: "front", fr: "avant" },
  { en: "nearby", fr: "proche" },
  { en: "opposite", fr: "opposé" },
  { en: "between", fr: "entre" },
  { en: "far", fr: "loin" },
  { en: "near", fr: "près" },
  { en: "under ", fr: "sous" },
  { en: "on", fr: "sur" },
  { en: "before", fr: "avant" },
  { en: "after", fr: "après" },
  { en: "park", fr: "parc" },
]

theMood = [
  { en: "happy", fr: "content" },
  { en: "hungry", fr: "affamé" },
  { en: "sad", fr: "triste" },
  { en: "angry", fr: "en colère" },
  { en: "thirsty", fr: "assoiffé" },
  { en: "tired", fr: "fatigué" },
]

theCharacteristics = [
  { en: "tall", fr: "grand" },
  { en: "short", fr: "petit" },
  { en: "athletic", fr: "athlétique" },
  { en: "handsome", fr: "beau" },
  { en: "pretty", fr: "jolie" },
  { en: "bald", fr: "chauve" },
  { en: "friendly", fr: "amical" },
  { en: "fat", fr: "gras" },
  { en: "cute", fr: "mignon" },
  { en: "shy", fr: "timide" },
  { en: "talkative", fr: "bavard" },
  { en: "clever", fr: "intelligent" },
  { en: "funny", fr: "drôle" },
  { en: "very", fr: "très" },
  { en: "small", fr: "petit" },
  { en: "large", fr: "large" },
  { en: "big", fr: "gros" },
]

theActions = [
  { en: "verb", fr: "verbe" },
  { en: "wait", fr: "attendre" },
  { en: "read", fr: "lire" },
  { en: "say", fr: "dire" },
  { en: "ask", fr: "demander" },
  { en: "answer", fr: "répondre" },
  { en: "know", fr: "savoir" },
  { en: "make", fr: "faire" },
  { en: "see", fr: "voir" },
  { en: "think", fr: "penser" },
  { en: "keep", fr: "garder" },
  { en: "talk", fr: "parler" },
  { en: "prepare", fr: "préparer" },
  { en: "try", fr: "essayer" },
  { en: "give", fr: "donner" },
  { en: "use", fr: "utiliser" },
  { en: "help", fr: "aider" },
  { en: "show", fr: "montrer" },
  { en: "describe", fr: "décrire" },
  { en: "organize ", fr: "organiser" },
  { en: "practice", fr: "pratiquer" },
  { en: "add", fr: "ajouter" },
  { en: "more", fr: "plus" },
  { en: "cook", fr: "cuisiner" },
  { en: "jog", fr: "faire du jogging" },
  { en: "run", fr: "courir" },
  { en: "knit", fr: "tricoter" },
  { en: "tell", fr: "dire" },
  { en: "drink", fr: "boire" },
  { en: "own", fr: "posséder" },
  { en: "sleep", fr: "dormir" },
  { en: "get up", fr: "se lever" },
  { en: "finish", fr: "finir" },
  { en: "start", fr: "commencer" },
  { en: "go", fr: "aller" },
  { en: "look", fr: "regarder" },
  { en: "slide", fr: "glisser" },
  { en: "know", fr: "savoir" },
  { en: "swim", fr: "nager" },
  { en: "find", fr: "trouver" },
  { en: "love", fr: "aimer" },
  { en: "play", fr: "jouer" },
  { en: "watch", fr: "regarder" },
  { en: "eat", fr: "manger" },
  { en: "prefer", fr: "préférer" },
  { en: "walk", fr: "marcher" },
  { en: "wake up", fr: "Se réveiller" },
  { en: "take", fr: "prendre" },
  { en: "listen", fr: "écouter" },
  { en: "hear", fr: "entendre" },
  { en: "put", fr: "mettre" },
  { en: "fall", fr: "tomber" },
  { en: "feel", fr: "se sentire" },
  { en: "buy", fr: "acheter" },
  { en: "order", fr: "commander" },
  { en: "attend", fr: "assister" },
  { en: "receive", fr: "recevoir" },
  { en: "decide", fr: "décider" },
  { en: "contract", fr: "contracter" },
  { en: "brush", fr: "brosser" },
  { en: "follow", fr: "suivre" },
]

theWordsElse = [
  { en: "text", fr: "texte" },
  { en: "someone / somebody", fr: "quelqu'un" },
  { en: "question", fr: "question" },
  { en: "these", fr: "ces" },
  { en: "this", fr: "ce" },
  { en: "conversation", fr: "conversation" },
  { en: "too", fr: "aussi" },
  { en: "any", fr: "n'importe lquel" },
  { en: "with", fr: "avec" },
  { en: "partner", fr: "partenaire" },
  { en: "useful", fr: "utile" },
  { en: "expression", fr: "expression" },
  { en: "activity", fr: "activité" },
  { en: "thank you", fr: "merci" },
  { en: "goodbye", fr: "au revoir" },
  { en: "soon", fr: "bientôt" },
  { en: "role", fr: "rôle" },
  { en: "student", fr: "étudiant" },
  { en: "conversation", fr: "conversation" },
  { en: "correction", fr: "corrigé" },
  { en: "mind", fr: "esprit" },
  { en: "new", fr: "nouveau" },
  { en: "module", fr: "module" },
  { en: "about", fr: "à propos" },
  { en: "people", fr: "personnes" },
  { en: "age", fr: "âge" },
  { en: "characteristic", fr: "caractéristique" },
  { en: "number", fr: "numéro" },
  { en: "allowed", fr: "autorisé" },
  { en: "pronunciation", fr: "prononciation" },
  { en: "old", fr: "vieux" },
  { en: "years", fr: "années" },
  { en: "sentence", fr: "phrase" },
  { en: "hair", fr: "cheveux" },
  { en: "eyes", fr: "yeux" },
  { en: "personality", fr: "personnalité " },
  { en: "not at all", fr: "pas du tout" },
  { en: "not very", fr: "pas vraiment / pas très" },
  { en: "quite", fr: "assez" },
  { en: "very", fr: "très" },
  { en: "experiment", fr: "expérience" },
  { en: "passionate", fr: "passionné" },
  { en: "brave", fr: "brave" },
  { en: "lazy", fr: "paresseux" },
  { en: "hobby", fr: "passe-temps" },
  { en: "sport", fr: "sport" },
  { en: "word", fr: "mot" },
  { en: "garden", fr: "jardin" },
  { en: "board games", fr: "jeux de société" },
  { en: "football", fr: "football" },
  { en: "like", fr: "aimer / comme" },
  { en: "book", fr: "livre" },
  { en: "type", fr: "type" },
  { en: "shoes", fr: "chaussures" },
  { en: "week", fr: "semaine" },
  { en: "weekend", fr: "week-end" },
  { en: "these", fr: "ces" },
  { en: "good", fr: "bien	" },
  { en: "dialogue", fr: "dialogue" },
  { en: "partner", fr: "partenaire" },
  { en: "idea", fr: "idée" },
  { en: "watch", fr: "montre" },
  { en: "TV", fr: "télévision" },
  { en: "home", fr: "maison" },
  { en: "house", fr: "logement" },
  { en: "lunch", fr: "déjeuner" },
  { en: "bed", fr: "lit" },
  { en: "teeth", fr: "dents" },
  { en: "tooth", fr: "dent" },
  { en: "then", fr: "alors" },
  { en: "until", fr: "jusqu'à" },
  { en: "around", fr: "autour" },
  { en: "shower", fr: "douche" },
  { en: "concert", fr: "concert" },
  { en: "great", fr: "super" },
  { en: "me", fr: "moi" },
  { en: "should", fr: "devrait" },
  { en: "restaurant", fr: "restaurant" },
  { en: "conversation", fr: "conversation" },
  { en: "teacher", fr: "professeur" },
  { en: "would", fr: "serait" },
  { en: "favorite", fr: "préféré" },
  { en: "food", fr: "nourriture" },
  { en: "kid", fr: "enfant" },
  { en: "video", fr: "vidéo" },
  { en: "worry", fr: "inquiétude" },
  { en: "understand", fr: "comprendre" },
  { en: "everything", fr: "tout" },
  { en: "order", fr: "commande" },
  { en: "again", fr: "encore" },
  { en: "script", fr: "scénario" },
  { en: "first", fr: "premièrement" },
  { en: "favorite", fr: "favori" },
  { en: "maybe", fr: "peut - être" },
  { en: "bottle", fr: "bouteille" },
  { en: "sir", fr: "monsieur" },
  { en: "get", fr: "obtenir" },
  { en: "please", fr: "s'il te plaît" },
  { en: "hot", fr: "chaud" },
  { en: "medium", fr: "moyen" },
  { en: "mild", fr: "léger" },
  { en: "ready", fr: "prêt" },
  { en: "yet", fr: "encore" },
  { en: "few", fr: "peu" },
  { en: "anything", fr: "quoi que ce soit" },
  { en: "glass", fr: "verre" },
  { en: "problem", fr: "problème" },
  { en: "picture", fr: "image" },
  { en: "usually", fr: "généralement" },
  { en: "done", fr: "fait" },
  { en: "never", fr: "jamais" },
  { en: "self", fr: "soi" },
  { en: "yourself", fr: "toi-même" },
  { en: "other", fr: "autre" },
  { en: "group", fr: "groupe" },
  { en: "some", fr: "quelques" },
  { en: "birth", fr: "naissance" },
  { en: "same", fr: "même" },
  { en: "there is", fr: "il y a" },
  { en: "there are", fr: "là / il y a" },
  { en: "there", fr: "là" },
  { en: "that's all", fr: "c'est tout" },
  { en: "fine", fr: "bien" },
  { en: "nice", fr: "bon" },
  { en: "What about you", fr: "et toi" },
  { en: "sure", fr: "bien sûr" },
  { en: "beautiful", fr: "beau" },
  { en: "but", fr: "mais" },
  { en: "live", fr: "habite" },
  { en: "travel", fr: "voyage" },
  { en: "town center", fr: "centre ville" },
  { en: "school", fr: "école" },
  { en: "taxi", fr: "taxi" },
  { en: "how about you", fr: "et toi" },
  { en: "pet", fr: "animal de compagnie" },
  { en: "story", fr: "histoire" },
  { en: "let's go", fr: "allons-y" },
  { en: "festival", fr: "festival" },
  { en: "program", fr: "programme" },
  { en: "start", fr: "commencer" },
  { en: "concert", fr: "concert" },
  { en: "classic", fr: "classique" },
  { en: "dance", fr: "danse" },
  { en: "barbecue", fr: "barbecure" },
  { en: "of course", fr: "bien sûr" },
  { en: "phone", fr: "téléphone" },
  { en: "table", fr: "table" },
  { en: "foot", fr: "pied" },
  { en: "bag", fr: "sac" },
  { en: "sofa / couch", fr: "canapé" },
  { en: "pocket", fr: "poche" },
  { en: "glasses", fr: "lunettes" },
  { en: "inside", fr: "à l'intérieur" },
  { en: "outside", fr: "dehors" },
  { en: "upstairs", fr: "à l'étage" },
  { en: "stairs", fr: "escaliers" },
  { en: "bathroom", fr: "salle de bains" },
  { en: "bath", fr: "bain" },
  { en: "room", fr: "chambre" },
  { en: "key", fr: "clé" },
  { en: "during", fr: "pendant" },
  { en: "take", fr: "prendre" },
  { en: "bus", fr: "bus" },
  { en: "tennis", fr: "tennis" },
  { en: "here", fr: "ici" },
  { en: "expensive", fr: "cher" },
  { en: "smile", fr: "sourire" },
  { en: "said", fr: "a dit" },
  { en: "really", fr: "vraiment" },
  { en: "ever", fr: "jamais" },
  { en: "which", fr: "qui" },
  { en: "right now", fr: "tout de suite" },
  { en: "normal", fr: "normal" },
  { en: "class", fr: "classe" },
  { en: "travel", fr: "voyage" },
  { en: "everyone", fr: "tout le monde" },
  { en: "typical", fr: "typique" },
  { en: "magazine", fr: "magazine" },
  { en: "life", fr: "vie" },
  { en: "office", fr: "bureau" },
  { en: "prefer", fr: "préférer" },
  { en: "bike", fr: "vélo" },
  { en: "minute", fr: "minute" },
  { en: "late", fr: "retard" },
  { en: "true", fr: "vrai" },
  { en: "false", fr: "faux" },
  { en: "early", fr: "tôt" },
  { en: "city", fr: "ville" },
  { en: "beautiful", fr: "beau" },
  { en: "motorbike", fr: "moto" },
  { en: "moment", fr: "moment" },
  { en: "ago", fr: "il y a" },
  { en: "call", fr: "appel" },
  { en: "grammar", fr: "grammaire" },
  { en: "rules", fr: "règles" },
  { en: "irregular", fr: "irrégulier" },
  { en: "regular", fr: "régulier" },
  { en: "into", fr: "dans" },
  { en: "correct", fr: "correct" },
  { en: "must", fr: "devoir" },
  { en: "obligation", fr: "obligation" },
  { en: "project", fr: "projet" },
  { en: "manager", fr: "directeur" },
  { en: "action", fr: "action" },
  { en: "spontaneous", fr: "spontané" },
  { en: "quick", fr: "rapide" },
  { en: "decision", fr: "décision" },
  { en: "expression", fr: "expression" },
  { en: "happen", fr: "arriver" },
  { en: "part", fr: "partie" },
  { en: "dinner", fr: "dîner" },
  { en: "seat", fr: "siège" },
]

//////////////////////// 

theColors = [

]

theSeasons = [

]

theObjects = [

]

theSports = [

]

theCountry = [

]

theFurniture = [

]